name: Call the reusable workflow

on: [push]

jobs:
  call-workflow-passing-data:
    uses: leshemo/WpfApplicationBuild/.github/workflows/Reusable-BuildRelease-dotnetFramework.yml@main
    with:
      slnName: WpfAppExpenseIt.sln
      filesToZipLocation: bin/Release
