name: Generic Build

#This action runs whenever something is pushed within the repository.
on: [push]


jobs:
  
  buildAndRelease:
    runs-on: windows-latest 

    steps:
    
      #checks the repository out onto the GitHub runner.
    - uses: actions/checkout@v3
    
      #sets up MSBuild in order to build the repo's sln file.
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      
      # all the powershell actions in the script, such as finding the sln file and creating the tag-name for the release.
    - name: Powershell actions
      run: |
        $slnName = Get-ChildItem -Path .\ -Filter *.sln -Recurse -File -Name
        $todaysDate = (Get-Date).ToUniversalTime().ToString("yyyy.MM.dd.HHmmss")
        $sha = "${{github.sha}}"
        $shortSha = $sha.Substring(0,8)
        $tagNameFull = $todaysDate + "-" + $shortSha
        echo "TAG_NAME=$tagNameFull" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

      #Building the solution
    - name: Build Solution
      run: msbuild.exe $slnName -t:rebuild -property:Configuration=Release

      #Zip up artifact file with action
    - name: Zip Artifact
      uses: vimtor/action-zip@v1
      with:
        files: bin/Release
        dest: artifacts.zip
    
      #Using the zip file and tag-name to craft the release.
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: "artifacts.zip"
        tag_name: "${{env.TAG_NAME}}"
